# -*- coding: utf-8 -*-

BYTECODE_SEND = 0
BYTECODE_SELFSEND = 1
BYTECODE_RESEND = 2
BYTECODE_PUSHSELF = 3
BYTECODE_PUSHLITERAL = 4
BYTECODE_POP = 5
BYTECODE_RETURNTOP = 6
BYTECODE_RETURNIMPLICIT = 7

LITERAL_TYPE_NIL = 0
LITERAL_TYPE_INT = 1
LITERAL_TYPE_STR = 2

SEND_TYPE_UNARY = 0
SEND_TYPE_BINARY = 1
SEND_TYPE_KEYWORD = 2
